# Find all distances between the houses from the distances of neighbours

In [65]:
import numpy as np
# Initialize a dataset
x = [1, 2, 1, 3]

In [69]:
# Initialize data structure to store distances
y1 = np.zeros((5,5))

for i in range(n):
    for j in range(i, n):
        temp = 0
        for k in range(i, j):
            temp += x[k]
        y1[i,j] = temp

print(y)
print(x)

[[0. 1. 3. 4. 7.]
 [0. 0. 2. 3. 6.]
 [0. 0. 0. 1. 4.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0.]]
[1, 2, 1, 3]


In [67]:
# When n = 5
print(x[0])
print(x[1])
print(x[0]+x[1]+x[2])
print(x[0]+x[1]+x[2]+x[3])

# Algorithm seems to be correct

1
2
4
7


In [76]:
# Initialize data structure to store distances
y2 = np.zeros((5,5))

for i in range(5):
    for j in range(i, 4):
        if i == 0:
            y2[i, j + 1] = x[j]
        else:
            y2[i, j + 1] = x[j] + y[i - 1, j]
print(y1)
print(y2)
print(x)
# Seems to be correct. Just that I have to convert diagonals to rows.

def ConvertAtoY(A,i,j):
    d = max(i,j) - min(i,j)
    print("this is d: " + str(d))
    return A[d, j]

print(ConvertAtoY(y2, 2, 3))


[[0. 1. 3. 4. 7.]
 [0. 0. 2. 3. 6.]
 [0. 0. 0. 1. 4.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 1. 3.]
 [0. 0. 3. 4. 7.]
 [0. 0. 0. 3. 6.]
 [0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0.]]
[1, 2, 1, 3]
this is d: 1
4.0


# We want to rent a room of exactly size s but we know that there is no such room available our second option is to rent 2 rooms which adds to exactly s

In [ ]:
# We re-use the data x from the problem above